```yaml
# ==========================================================
# Customer Rules
# ==========================================================

customers:

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: customer_id
      criticality: error
      name: customer_id_not_null

  - check:
      function: is_unique
      arguments:
        column: customer_id
      criticality: error
      name: customer_id_unique

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: customer_unique_id
      criticality: error
      name: customer_unique_id_not_null

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: city
      criticality: warn
      name: city_not_null

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: state
      criticality: warn
      name: state_not_null


# ==========================================================
# Product Rules
# ==========================================================

products:

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: product_id
      criticality: error
      name: product_id_not_null

  - check:
      function: is_unique
      arguments:
        column: product_id
      criticality: error
      name: product_id_unique

  - check:
      function: is_in_range
      arguments:
        column: weight_kg
        min_limit: 0.01
      criticality: error
      name: valid_weight

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: category
      criticality: warn
      name: category_not_null


# ==========================================================
# Seller Rules
# ==========================================================

sellers:

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: seller_id
      criticality: error
      name: seller_id_not_null

  - check:
      function: is_unique
      arguments:
        column: seller_id
      criticality: error
      name: seller_id_unique

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: city
      criticality: warn
      name: city_not_null

  - check:
      function: is_not_null_and_not_empty
      arguments:
        column: state
      criticality: warn
      name: state_not_null
```
